### ISSUE TITLE
我把前端Proxy放开后，登录后台还是提示跨域？

### ISSUE THREAD

**Issue by ExhaustiveMethod** [TyCoding/tumo-vue#11]
把前端Proxy全局跨域打开后，登录后台的/login网页，点击登录提示连接异常，请稍后再试。
网页其他部分都是正常的
<img width="427" alt="捕获" src="https://user-images.githubusercontent.com/41338498/88480057-40537500-cf86-11ea-8568-d25050fc99e4.PNG">
<img width="850" alt="捕获1" src="https://user-images.githubusercontent.com/41338498/88480062-434e6580-cf86-11ea-9731-2bd115b22f0d.PNG">
<img width="902" alt="捕获2" src="https://user-images.githubusercontent.com/41338498/88480064-45182900-cf86-11ea-98bf-9ca1eedec73e.PNG">
<img width="859" alt="捕获3" src="https://user-images.githubusercontent.com/41338498/88480065-45b0bf80-cf86-11ea-81e0-cb939fcc8664.PNG">

**Comment by yangslhappy** [comment]
我也是

**Comment by TyCoding** [comment]
@yutao331763646 @ExhaustiveMethod  跨域问题已解决，请看`/app/vue.config.js` 中proxy的配置。
如果还有问题请反馈

**Comment by ExhaustiveMethod** [comment]
@TyCoding 已经可以登录，感谢！

**Comment by yangslhappy** [comment]
@TyCoding 感谢！
